name: 'Deploy'

on:
    release:
        types: [published]
    push:
        branches: ['main']
    workflow_dispatch:

jobs:
    vercel:
        runs-on: ubuntu-18.04
        name: 'Deploy application'

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: 'Deploy application'
              run: |
                  prodRun=""
                  if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
                    prodRun="--prod"
                  fi

                  pnpm vercel --yes --token ${VERCEL_TOKEN} $prodRun
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
